// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZZQVJpVWXX2EGfFkEuFPZu0XgcLhUTKY',
    appId: '1:518800710686:web:79b866f217360fa4ed620f',
    messagingSenderId: '518800710686',
    projectId: 'app1-c8a74',
    authDomain: 'app1-c8a74.firebaseapp.com',
    storageBucket: 'app1-c8a74.appspot.com',
    measurementId: 'G-1P82KTMCKT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2bJsLWKtdk5fbxo3KZ5GGllmLLZtrOYI',
    appId: '1:518800710686:android:e5dd2d382c7f3659ed620f',
    messagingSenderId: '518800710686',
    projectId: 'app1-c8a74',
    storageBucket: 'app1-c8a74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4awUfMAX3z2qQmxzw1VAjMxlieRZKxcA',
    appId: '1:518800710686:ios:e13d637d7772c566ed620f',
    messagingSenderId: '518800710686',
    projectId: 'app1-c8a74',
    storageBucket: 'app1-c8a74.appspot.com',
    iosClientId: '518800710686-tmg6ng9k489hrjm24hg5eu4fubtrvdvo.apps.googleusercontent.com',
    iosBundleId: 'com.example.signuplogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4awUfMAX3z2qQmxzw1VAjMxlieRZKxcA',
    appId: '1:518800710686:ios:e13d637d7772c566ed620f',
    messagingSenderId: '518800710686',
    projectId: 'app1-c8a74',
    storageBucket: 'app1-c8a74.appspot.com',
    iosClientId: '518800710686-tmg6ng9k489hrjm24hg5eu4fubtrvdvo.apps.googleusercontent.com',
    iosBundleId: 'com.example.signuplogin',
  );
}
